export const Books = [
  {
    id: 1,
    url: "image/book-1.png",
    title: "the art city",
    price: "$20.99",
    dis_price: 15,
    inCart:false,
  },
  {
    id: 2,
    url: "image/book-2.png",
    title: "thanks in everything",
    price: "$49.99",
    dis_price: 33,
    inCart:false,
  },
  {
    id: 3,
    url: "image/book-3.png",
    title: "your name",
    price: "$20.99",
    dis_price: 15,
    inCart:false,
  },
  {
    id: 4,
    url: "image/book-4.png",
    title: "peoples hands",
    price: "$10.99",
    dis_price: 5,
    inCart:false,
  },
  {
    id: 5,
    url: "image/book-5.png",
    title: "music rock",
    price: "$24.99",
    dis_price: 19,
    inCart:false,
  },
  {
    id: 6,
    url: "image/book-6.png",
    title: "green book",
    price: "$9.99",
    dis_price: 4,
    inCart:false,
  },
  {
    id: 7,
    url: "image/book-7.png",
    title: "light house",
    price: "$13.99",
    dis_price: 9,
    inCart:false,
  },
  {
    id: 8,
    url: "image/book-8.png",
    title: "black history month",
    price: "$11.99",
    dis_price: 6,
    inCart:false,
  },
  {
    id: 9,
    url: "image/book-9.png",
    title: "love",
    price: "$21.99",
    dis_price: 17,
    inCart:false,
  },
  {
    id: 10,
    url: "image/book-10.png",
    title: "retro",
    price: "$18.99",
    dis_price: 13,
    inCart:false,
  },
];

export const Clients = [
  { id: 11, url: "image/pic-1.png", name: "John Deo" },
  { id: 12, url: "image/pic-2.png", name: "Marry Jain" },
  { id: 13, url: "image/pic-3.png", name: "Petter Parker" },
  { id: 14, url: "image/pic-4.png", name: "Olivia Whitehead" },
  { id: 15, url: "image/pic-5.png", name: "Thomas Charles" },
  { id: 16, url: "image/pic-6.png", name: "Ava Stark" },
];

export const BlogList = [
  { id: 21, url: "image/blog-1.jpg", heading: "Into the books" },
  { id: 22, url: "image/blog-2.jpg", heading: "light your path" },
  { id: 23, url: "image/blog-3.jpg", heading: "flying kites" },
  { id: 24, url: "image/blog-4.jpg", heading: "happiness" },
  { id: 25, url: "image/blog-5.jpg", heading: "under the stars" },
];
